### PR TITLE
Add video capturing source module

### PR DESCRIPTION
**Pull request by SimonTaoEMC**
Add a new source module in folder of videocap, this module grabs JPEG-encoded image from camera or video file, thus serves as the source module for video ingestion/processing.

I have signed and agree to the terms of the SpringSource Individual
Contributor License Agreement. 
[CLA number: 120420150514085534]

### CODE REVIEW

**Comment by thomasdarimont** [comment]
Hi Simon,

Would you mind adding you CLA number to the PR comment?
I gave your module a spin and polished it a bit - feel free to grab the commit: https://github.com/thomasdarimont/spring-xd-modules/commit/b9eb92b6df9cee05ee51a2118f12b409553df37b

Cheers,
Thomas

**Comment by SimonTaoEMC** [comment]
Hi Thomas,

CLA number is added to the first comment.
Thanks for all these good staffs from your branch!

Cheers,
Simon

**Comment by thomasdarimont** [comment]
You're welcome! :)

I tried to follow @ericbottard's recommendation of using @Mixin(PeriodicTriggerMixin.class) in the options, but it turns out that this would make the module incompatible with Spring XD 1.2.x due to the a package change: 
1.1.2.Release: org.springframework.xd.dirt.modules.metadata.PeriodicTriggerMixin
1.2.M1: org.springframework.xd.module.options.mixins.PeriodicTriggerMixin

One gets a "Command failed org.springframework.xd.rest.client.impl.SpringXDException: sun.reflect.annotation.TypeNotPresentExceptionProxy" exception if one tries to deploy such a module in XD 1.2.x
If I use the class from XD 1.2.x I have the problem in reverse with XD 1.1.x.

So I'd leave this as is for now.

Besides that PR LGTM.

Shall I merge the PR into master?

**Comment by thomasdarimont** [comment]
Hi @SimonTaoEMC,

I got a go from @sabbyanandan to merge this into master. I opened up a new PR (#17) since I polished the git commits a bit (added reference to JIRA issue) and setup a new branch *feature/video-capture-source* that we can use for further enhancements.

Thanks for your contribution! :+1: 

Cheers,
Thomas

**Comment by SimonTaoEMC** [comment]
Cheers!
Hope we can continue to add more features in Spring-XD for video ingestion and processing later on.

Thanks,
Simon

**Pull request closed without merging**
